name: Auto-delete merged branches (except dev/stable/etc)

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  delete_branch:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        id: vars
        run: echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT

      - name: Check if branch should be skipped
        id: skip
        run: |
          BRANCH="${{ steps.vars.outputs.branch }}"
          echo "Checking if branch '$BRANCH' should be excluded from deletion..."
          case "$BRANCH" in
            dev|stable|main|master|release/*)
              echo "skip=true" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "skip=false" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Delete branch
        if: steps.skip.outputs.skip == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="${{ steps.vars.outputs.branch }}"
          echo "Deleting branch '$BRANCH'..."
          curl -s -X DELETE \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH
