# .github/workflows/rebase-dev-onto-main.yml
name: Rebase dev onto main

on:
  push:
    branches: [main]

concurrency:
  group: rebase-dev-onto-main
  cancel-in-progress: true

jobs:
  rebase:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Reset to remote dev
        run: |
          git fetch origin
          git reset --hard origin/dev

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase onto main
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Force push dev
        run: |
          git push origin dev --force-with-lease
